(* Auto-generated by generate_seed_packages.py. *)
(* seed_family: unary_binary_naturals *)
(* feature: representation equivalence smoke transfer *)

From Coq Require Import Arith.PeanoNat.
From Coq Require Import NArith.

Definition unary_binary_rel (n : nat) (m : N) : Prop :=
  m = N.of_nat n.

Lemma generated_zero_transfer :
  unary_binary_rel 0 0%N.
Proof.
  reflexivity.
Qed.

Lemma generated_succ_transfer :
  forall n m,
    unary_binary_rel n m ->
    unary_binary_rel (S n) (N.succ m).
Proof.
  intros n m H.
  unfold unary_binary_rel in *.
  subst.
  rewrite Nat2N.inj_succ.
  reflexivity.
Qed.

Lemma generated_plus_transfer :
  forall a b ma mb,
    unary_binary_rel a ma ->
    unary_binary_rel b mb ->
    unary_binary_rel (a + b) (ma + mb)%N.
Proof.
  intros a b ma mb Ha Hb.
  unfold unary_binary_rel in *.
  subst.
  rewrite Nat2N.inj_add.
  reflexivity.
Qed.
