(* Auto-generated by generate_seed_packages.py. *)
(* seed_family: modulo_arithmetic *)
(* feature: retraction-style modulo carrier *)

From Coq Require Import Arith.PeanoNat.

Definition mod_rel (m x y : nat) : Prop :=
  y = x mod m.

Lemma generated_mod_intro :
  forall m x, mod_rel m x (x mod m).
Proof.
  intros; unfold mod_rel; reflexivity.
Qed.

Lemma generated_mod_idempotent :
  forall m x y,
    m <> 0 ->
    mod_rel m x y ->
    mod_rel m y y.
Proof.
  intros m x y Hm H.
  unfold mod_rel in *.
  subst.
  rewrite Nat.mod_mod by exact Hm.
  reflexivity.
Qed.

Lemma generated_mod_eq_transport :
  forall m x x' y,
    x = x' ->
    mod_rel m x y ->
    mod_rel m x' y.
Proof.
  intros m x x' y Hx H.
  subst.
  exact H.
Qed.
