from __future__ import annotations

import hashlib
import json
import re
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any


STRENGTHS = {"plain", "section", "retraction", "equivalence", "logical"}
REQUIRED_LAWS = {
    "plain": set(),
    "logical": {"logical"},
    "section": {"section"},
    "retraction": {"retraction"},
    "equivalence": {"section", "retraction"},
}


class SpecError(ValueError):
    pass


@dataclass(frozen=True)
class Decision:
    outcome: str
    required_axioms: tuple[str, ...]
    blocked_axioms: tuple[str, ...]


def load_spec(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SpecError(f"cannot read specification {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise SpecError("the top-level JSON value must be an object")
    return data


def infer_strength(laws: list[dict[str, Any]], requested: str | None = None) -> str:
    kinds = {str(item.get("kind", "")).lower() for item in laws}
    if requested:
        requested = requested.lower()
        if requested not in STRENGTHS:
            raise SpecError(f"unknown relation strength: {requested}")
        missing = REQUIRED_LAWS[requested] - kinds
        if missing:
            raise SpecError(
                f"strength {requested} requires law kinds: {', '.join(sorted(missing))}"
            )
        return requested
    if {"section", "retraction"} <= kinds:
        return "equivalence"
    if "section" in kinds:
        return "section"
    if "retraction" in kinds:
        return "retraction"
    if "logical" in kinds:
        return "logical"
    return "plain"


def policy_decision(spec: dict[str, Any]) -> Decision:
    required = tuple(sorted(set(map(str, spec.get("required_axioms", [])))))
    allowed = set(map(str, spec.get("policy", {}).get("allowed_axioms", [])))
    blocked = tuple(item for item in required if item not in allowed)
    return Decision(
        outcome="safe_reject" if blocked else "accept",
        required_axioms=required,
        blocked_axioms=blocked,
    )


def _identifier(value: str, field: str) -> str:
    if not re.fullmatch(r"[A-Za-z][A-Za-z0-9_']*", value):
        raise SpecError(f"{field} is not a valid Coq identifier: {value!r}")
    return value


def validate_spec(spec: dict[str, Any]) -> tuple[str, str, Decision]:
    module = _identifier(str(spec.get("module", "")), "module")
    for field in ("source_type", "target_type", "relation"):
        if not str(spec.get(field, "")).strip():
            raise SpecError(f"missing non-empty field: {field}")
    laws = spec.get("laws", [])
    if not isinstance(laws, list):
        raise SpecError("laws must be a JSON array")
    for law in laws:
        if not isinstance(law, dict):
            raise SpecError("each law must be a JSON object")
        _identifier(str(law.get("name", "")), "law name")
        for field in ("kind", "statement", "proof"):
            if not str(law.get(field, "")).strip():
                raise SpecError(f"law {law.get('name', '<unnamed>')} lacks {field}")
    strength = infer_strength(laws, spec.get("requested_strength"))
    return module, strength, policy_decision(spec)


def render_coq(spec: dict[str, Any], strength: str) -> str:
    module = str(spec["module"])
    imports = [str(item) for item in spec.get("imports", [])]
    lines = [
        "(* Generated by AutoTrocq 0.1.1. *)",
        f"(* RELATION_STRENGTH: {strength} *)",
        f"(* REQUIRED_AXIOMS: {', '.join(map(str, spec.get('required_axioms', []))) or 'none'} *)",
        "",
    ]
    lines.extend(f"Require Import {item}." for item in imports)
    if imports:
        lines.append("")
    lines.extend(
        [
            f"Module {module}.",
            f"Definition Source : Type := {spec['source_type']}.",
            f"Definition Target : Type := {spec['target_type']}.",
            f"Definition transfer_rel : Source -> Target -> Prop := {spec['relation']}.",
        ]
    )
    definitions = spec.get("definitions", [])
    if definitions:
        lines.append("")
        lines.extend(str(item).rstrip() for item in definitions)
    for law in spec.get("laws", []):
        lines.extend(
            [
                "",
                f"Theorem {law['name']} : {law['statement']}.",
                "Proof.",
                str(law["proof"]).strip(),
                "Qed.",
            ]
        )
    lines.extend(["", f"End {module}.", ""])
    return "\n".join(lines)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def generate(spec_path: Path, out_dir: Path) -> dict[str, Any]:
    spec = load_spec(spec_path)
    module, strength, decision = validate_spec(spec)
    out_dir.mkdir(parents=True, exist_ok=True)
    report: dict[str, Any] = {
        "schema_version": 1,
        "module": module,
        "relation_strength": strength,
        "required_axioms": list(decision.required_axioms),
        "blocked_axioms": list(decision.blocked_axioms),
        "policy_outcome": decision.outcome,
        "source_spec": spec_path.name,
    }
    if decision.outcome == "accept":
        coq_path = out_dir / f"{module}.v"
        coq_path.write_text(render_coq(spec, strength), encoding="ascii", newline="\n")
        report["generated_file"] = coq_path.name
        report["generated_sha256"] = sha256(coq_path)
    else:
        report["diagnostic"] = "axiom policy blocks the requested package"
    report_path = out_dir / f"{module}.manifest.json"
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return report


def _run(command: list[str], cwd: Path) -> dict[str, Any]:
    started = time.perf_counter()
    proc = subprocess.run(
        command,
        cwd=cwd,
        text=True,
        encoding="utf-8",
        errors="replace",
        capture_output=True,
        check=False,
    )
    return {
        "command": command,
        "returncode": proc.returncode,
        "elapsed_seconds": round(time.perf_counter() - started, 6),
        "stdout": proc.stdout,
        "stderr": proc.stderr,
    }


def replay(coq_file: Path, report_path: Path | None = None) -> dict[str, Any]:
    coq_file = coq_file.resolve()
    if not coq_file.is_file():
        raise SpecError(f"Coq file does not exist: {coq_file}")
    if shutil.which("coqc") is None or shutil.which("coqchk") is None:
        raise SpecError("coqc and coqchk must both be available on PATH")
    compile_result = _run(["coqc", "-q", coq_file.name], coq_file.parent)
    module = coq_file.stem
    check_result = None
    if compile_result["returncode"] == 0:
        check_result = _run(["coqchk", module], coq_file.parent)
    outcome = (
        "kernel_success"
        if compile_result["returncode"] == 0
        and check_result is not None
        and check_result["returncode"] == 0
        else "kernel_failure"
    )
    report = {
        "schema_version": 1,
        "module": module,
        "coq_file": coq_file.name,
        "coq_sha256": sha256(coq_file),
        "outcome": outcome,
        "coqc": compile_result,
        "coqchk": check_result,
    }
    if report_path:
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return report


def doctor() -> dict[str, Any]:
    result: dict[str, Any] = {"autotrocq": "0.1.1"}
    for command in ("python", "coqc", "coqchk"):
        path = sys.executable if command == "python" else shutil.which(command)
        item: dict[str, Any] = {"path": path, "available": bool(path)}
        if path:
            probe = subprocess.run(
                [command, "--version"],
                text=True,
                encoding="utf-8",
                errors="replace",
                capture_output=True,
                check=False,
            )
            item["version"] = (probe.stdout or probe.stderr).strip().splitlines()[0]
        result[command] = item
    return result
