from __future__ import annotations

import hashlib
import csv
import json
import re
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any


STRENGTHS = {"plain", "section", "retraction", "equivalence", "logical"}
REQUIRED_LAWS = {
    "plain": set(),
    "logical": {"logical"},
    "section": {"section"},
    "retraction": {"retraction"},
    "equivalence": {"section", "retraction"},
}


class SpecError(ValueError):
    pass


@dataclass(frozen=True)
class Decision:
    outcome: str
    required_axioms: tuple[str, ...]
    blocked_axioms: tuple[str, ...]


def load_spec(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SpecError(f"cannot read specification {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise SpecError("the top-level JSON value must be an object")
    return data


def infer_strength(laws: list[dict[str, Any]], requested: str | None = None) -> str:
    kinds = {str(item.get("kind", "")).lower() for item in laws}
    if requested:
        requested = requested.lower()
        if requested not in STRENGTHS:
            raise SpecError(f"unknown relation strength: {requested}")
        missing = REQUIRED_LAWS[requested] - kinds
        if missing:
            raise SpecError(
                f"strength {requested} requires law kinds: {', '.join(sorted(missing))}"
            )
        return requested
    if {"section", "retraction"} <= kinds:
        return "equivalence"
    if "section" in kinds:
        return "section"
    if "retraction" in kinds:
        return "retraction"
    if "logical" in kinds:
        return "logical"
    return "plain"


def policy_decision(spec: dict[str, Any]) -> Decision:
    required = tuple(sorted(set(map(str, spec.get("required_axioms", [])))))
    allowed = set(map(str, spec.get("policy", {}).get("allowed_axioms", [])))
    blocked = tuple(item for item in required if item not in allowed)
    return Decision(
        outcome="safe_reject" if blocked else "accept",
        required_axioms=required,
        blocked_axioms=blocked,
    )


def composition_policy_decision(
    specs: list[dict[str, Any]], allowed_axioms: list[str]
) -> Decision:
    """Apply one policy to the exact union of a nonempty certificate chain."""
    if not specs:
        raise SpecError("a composition requires at least one package specification")
    required = tuple(
        sorted(
            {
                str(axiom)
                for spec in specs
                for axiom in spec.get("required_axioms", [])
            }
        )
    )
    allowed = set(map(str, allowed_axioms))
    blocked = tuple(axiom for axiom in required if axiom not in allowed)
    return Decision(
        outcome="safe_reject" if blocked else "accept",
        required_axioms=required,
        blocked_axioms=blocked,
    )


def _identifier(value: str, field: str) -> str:
    if not re.fullmatch(r"[A-Za-z][A-Za-z0-9_']*", value):
        raise SpecError(f"{field} is not a valid Coq identifier: {value!r}")
    return value


def validate_spec(spec: dict[str, Any]) -> tuple[str, str, Decision]:
    module = _identifier(str(spec.get("module", "")), "module")
    for field in ("source_type", "target_type", "relation"):
        if not str(spec.get(field, "")).strip():
            raise SpecError(f"missing non-empty field: {field}")
    laws = spec.get("laws", [])
    if not isinstance(laws, list):
        raise SpecError("laws must be a JSON array")
    for law in laws:
        if not isinstance(law, dict):
            raise SpecError("each law must be a JSON object")
        _identifier(str(law.get("name", "")), "law name")
        for field in ("kind", "statement", "proof"):
            if not str(law.get(field, "")).strip():
                raise SpecError(f"law {law.get('name', '<unnamed>')} lacks {field}")
    strength = infer_strength(laws, spec.get("requested_strength"))
    return module, strength, policy_decision(spec)


def render_coq(spec: dict[str, Any], strength: str) -> str:
    module = str(spec["module"])
    imports = [str(item) for item in spec.get("imports", [])]
    lines = [
        "(* Generated by AutoTrocq 0.3.0. *)",
        f"(* RELATION_STRENGTH: {strength} *)",
        f"(* REQUIRED_AXIOMS: {', '.join(map(str, spec.get('required_axioms', []))) or 'none'} *)",
        "",
    ]
    lines.extend(f"Require Import {item}." for item in imports)
    if imports:
        lines.append("")
    lines.extend(
        [
            f"Module {module}.",
            f"Definition Source : Type := {spec['source_type']}.",
            f"Definition Target : Type := {spec['target_type']}.",
            f"Definition transfer_rel : Source -> Target -> Prop := {spec['relation']}.",
        ]
    )
    definitions = spec.get("definitions", [])
    if definitions:
        lines.append("")
        lines.extend(str(item).rstrip() for item in definitions)
    for law in spec.get("laws", []):
        lines.extend(
            [
                "",
                f"Theorem {law['name']} : {law['statement']}.",
                "Proof.",
                str(law["proof"]).strip(),
                "Qed.",
            ]
        )
    lines.extend(["", f"End {module}.", ""])
    return "\n".join(lines)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def generate(spec_path: Path, out_dir: Path) -> dict[str, Any]:
    spec = load_spec(spec_path)
    module, strength, decision = validate_spec(spec)
    out_dir.mkdir(parents=True, exist_ok=True)
    report: dict[str, Any] = {
        "schema_version": 1,
        "module": module,
        "relation_strength": strength,
        "required_axioms": list(decision.required_axioms),
        "blocked_axioms": list(decision.blocked_axioms),
        "policy_outcome": decision.outcome,
        "source_spec": spec_path.name,
    }
    if decision.outcome == "accept":
        coq_path = out_dir / f"{module}.v"
        coq_path.write_text(render_coq(spec, strength), encoding="ascii", newline="\n")
        report["generated_file"] = coq_path.name
        report["generated_sha256"] = sha256(coq_path)
    else:
        report["diagnostic"] = "axiom policy blocks the requested package"
    report_path = out_dir / f"{module}.manifest.json"
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return report


def _run(command: list[str], cwd: Path) -> dict[str, Any]:
    started = time.perf_counter()
    proc = subprocess.run(
        command,
        cwd=cwd,
        text=True,
        encoding="utf-8",
        errors="replace",
        capture_output=True,
        check=False,
    )
    return {
        "command": command,
        "returncode": proc.returncode,
        "elapsed_seconds": round(time.perf_counter() - started, 6),
        "stdout": proc.stdout,
        "stderr": proc.stderr,
    }


def replay(coq_file: Path, report_path: Path | None = None) -> dict[str, Any]:
    coq_file = coq_file.resolve()
    if not coq_file.is_file():
        raise SpecError(f"Coq file does not exist: {coq_file}")
    if shutil.which("coqc") is None or shutil.which("coqchk") is None:
        raise SpecError("coqc and coqchk must both be available on PATH")
    compile_result = _run(["coqc", "-q", coq_file.name], coq_file.parent)
    module = coq_file.stem
    check_result = None
    if compile_result["returncode"] == 0:
        check_result = _run(["coqchk", module], coq_file.parent)
    outcome = (
        "kernel_success"
        if compile_result["returncode"] == 0
        and check_result is not None
        and check_result["returncode"] == 0
        else "kernel_failure"
    )
    report = {
        "schema_version": 1,
        "module": module,
        "coq_file": coq_file.name,
        "coq_sha256": sha256(coq_file),
        "outcome": outcome,
        "coqc": compile_result,
        "coqchk": check_result,
    }
    if report_path:
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return report


def batch(spec_dir: Path, out_dir: Path, replay_accepted: bool = True) -> dict[str, Any]:
    """Generate and optionally replay every JSON package in ``spec_dir``.

    Safe policy rejections are expected outcomes. Invalid specifications and
    failed kernel replays are retained as unexpected failures so a batch run
    cannot silently turn them into successful evidence.
    """
    spec_dir = spec_dir.resolve()
    out_dir = out_dir.resolve()
    if not spec_dir.is_dir():
        raise SpecError(f"specification directory does not exist: {spec_dir}")
    spec_paths = sorted(spec_dir.glob("*.json"))
    if not spec_paths:
        raise SpecError(f"no JSON specifications found in: {spec_dir}")
    out_dir.mkdir(parents=True, exist_ok=True)

    rows: list[dict[str, Any]] = []
    for spec_path in spec_paths:
        case_dir = out_dir / spec_path.stem
        try:
            generated = generate(spec_path, case_dir)
        except SpecError as exc:
            rows.append(
                {
                    "spec": spec_path.name,
                    "module": "",
                    "relation_strength": "",
                    "policy_outcome": "invalid_spec",
                    "blocked_axioms": "",
                    "coqc_returncode": "",
                    "coqchk_returncode": "",
                    "coqc_seconds": "",
                    "coqchk_seconds": "",
                    "final_outcome": "unexpected_invalid_spec",
                    "diagnostic": str(exc),
                }
            )
            continue

        row: dict[str, Any] = {
            "spec": spec_path.name,
            "module": generated["module"],
            "relation_strength": generated["relation_strength"],
            "policy_outcome": generated["policy_outcome"],
            "blocked_axioms": ";".join(generated["blocked_axioms"]),
            "coqc_returncode": "",
            "coqchk_returncode": "",
            "coqc_seconds": "",
            "coqchk_seconds": "",
            "final_outcome": "",
            "diagnostic": generated.get("diagnostic", ""),
        }
        if generated["policy_outcome"] == "safe_reject":
            row["final_outcome"] = "safe_reject_policy_blocked"
        elif not replay_accepted:
            row["final_outcome"] = "accepted_generated"
        else:
            coq_path = case_dir / generated["generated_file"]
            replay_report = replay(coq_path, case_dir / f"{generated['module']}.replay.json")
            row["coqc_returncode"] = replay_report["coqc"]["returncode"]
            row["coqchk_returncode"] = (
                replay_report["coqchk"]["returncode"] if replay_report["coqchk"] else ""
            )
            row["coqc_seconds"] = replay_report["coqc"]["elapsed_seconds"]
            row["coqchk_seconds"] = (
                replay_report["coqchk"]["elapsed_seconds"] if replay_report["coqchk"] else ""
            )
            row["final_outcome"] = (
                "accepted_kernel_checked"
                if replay_report["outcome"] == "kernel_success"
                else "unexpected_kernel_failure"
            )
        rows.append(row)

    fields = [
        "spec",
        "module",
        "relation_strength",
        "policy_outcome",
        "blocked_axioms",
        "coqc_returncode",
        "coqchk_returncode",
        "coqc_seconds",
        "coqchk_seconds",
        "final_outcome",
        "diagnostic",
    ]
    with (out_dir / "batch_results.csv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)

    outcome_counts: dict[str, int] = {}
    strength_counts: dict[str, int] = {}
    for row in rows:
        outcome = str(row["final_outcome"])
        strength = str(row["relation_strength"])
        outcome_counts[outcome] = outcome_counts.get(outcome, 0) + 1
        if strength:
            strength_counts[strength] = strength_counts.get(strength, 0) + 1
    unexpected = sum(count for name, count in outcome_counts.items() if name.startswith("unexpected_"))
    summary = {
        "schema_version": 1,
        "specifications": len(rows),
        "replay_accepted": replay_accepted,
        "outcomes": dict(sorted(outcome_counts.items())),
        "relation_strengths": dict(sorted(strength_counts.items())),
        "unexpected_failures": unexpected,
        "status": "success" if unexpected == 0 else "failure",
        "results_csv": "batch_results.csv",
    }
    (out_dir / "batch_summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return summary


def doctor() -> dict[str, Any]:
    result: dict[str, Any] = {"autotrocq": "0.3.0"}
    for command in ("python", "coqc", "coqchk"):
        path = sys.executable if command == "python" else shutil.which(command)
        item: dict[str, Any] = {"path": path, "available": bool(path)}
        if path:
            probe = subprocess.run(
                [command, "--version"],
                text=True,
                encoding="utf-8",
                errors="replace",
                capture_output=True,
                check=False,
            )
            item["version"] = (probe.stdout or probe.stderr).strip().splitlines()[0]
        result[command] = item
    return result
